[package]
name = "l3"
version = "0.1.0"
edition = "2024"

[lib]
name = "l3"
path = "src/lib.rs"

[[bin]]
name = "l3"
path = "src/main.rs"

[dependencies]
json = "0.12.4"
serde = { version = "1.0.225", features = ["serde_derive"] }
serde_json = "1.0.145"
