[package]
name = "hw6120"
version = "0.1.0"
edition = "2024"

[dependencies]
bpaf = { version = "0.9.20", features = ["autocomplete"] }
serde = { version = "1.0.226", features = ["serde_derive"] }
serde_json = "1.0.145"
